# Brief description of current directory files

./man.txt2tags
==============
Manually editable text file, designed to be converted into standard
man page through `./update-man.sh`.
It uses txt2tags markup syntax.


./update-man.sh
===============
Generate 'phpsploit.1' and 'phpsploit.txt' from 'man.txt2tags'.


./phpsploit.1
=============
Man page generated by `./update-man.sh`
(do not edit by hand !)


./phpsploit.txt
===============
Textual man page generated by `./update-man.sh`
(do not edit by hand !)
