# engines:
#   duplication:
#     enabled: true
#     config:
#       languages:
#         python:
#           python_version: 3

plugins:
  pep8:
    enabled: true
  radon: 
    enabled: true
  sonar-python:
    enabled: true

exclude_patterns:
  - 'deps/'
  - 'plugins/'
  - 'test/'
  - 'utils/'
  - 'data/'
  - 'man/'
