path_classifiers:
# https://lgtm.com/help/lgtm/file-classification
  test:
    - exclude: / # ignore lgtm test code default classification
    - test
    - utils
  docs:
    - man
    - doc
  library:
    - deps

extraction:
  python:
    python_setup:
      # analyse source as python3
      version: 3
    index:
      exclude:
        - deps
