Basic commands
==============

    Command        Description
    -------        -----------
    clear          Clear the terminal screen
    exit           Leave the phpsploit framework
    exploit        Drop a shell from target server
    help           Show this help message
    infect         Print the working backdoor
    save           Save the current session in file
    set            View and edit settings
