Basic commands
==============

    Command        Description
    -------        -----------
    clear          Clear the terminal screen
    exit           Leave the phpsploit framework
    exploit        Get a shell from target server
    help           Show this help message
    infect         Generate a backdoor for targeted URL
    save           Save the current session in file
    set            View and edit settings
